/**
 * Author: luisliu
 * Description: theme vars in js
 * Time: 2022-03-19 11:46:48
 * Contact: lc63msn@Hotmail.com
 */
import { Levels, Status, Actions, Sizes } from '../factors';

const PubSizing = Sizes({
  base: '0.1rem',
  bit: '0.1rem',
  mini: '0.2rem',
  small: '0.3rem',
  medium: '0.5rem',
  large: '0.8rem',
  huge: '1rem',
  super: '2rem',
})

export default {
  backgrounds: {
    ...Status({
      default: 'string',
      light: 'string',
      deep: 'string',
      normal: 'string',
      most: 'string',
      more: 'string',
      main: 'string',
      second: 'string',
      sub: 'string',
      last: 'string',
    }),
    gradients: Status({
      default: '',
      light: 'linear-gradient(0deg, rgba(32, 111, 223, 0.5) 0%, #206fdf 53%, rgba(32, 111, 223, 0.5) 100%)',
      deep: 'linear-gradient(0deg, rgba(32, 111, 223, 0.5) 0%, #206fdf 53%, rgba(32, 111, 223, 0.5) 100%)',
      normal: 'string',
      most: 'string',
      more: 'string',
      main: 'string',
      second: 'string',
      sub: 'string',
      last: 'string',
    }),
    images: Status({
      default: 'string',
      light: 'string',
      deep: 'string',
      normal: 'string',
      most: 'string',
      more: 'string',
      main: 'string',
      second: 'string',
      sub: 'string',
      last: 'string',
    }),
    hover: Status({
      default: 'string',
      light: 'string',
      deep: 'string',
      normal: 'string',
      most: 'string',
      more: 'string',
      main: 'string',
      second: 'string',
      sub: 'string',
      last: 'string',
    }),
    focus: Status({
      default: 'string',
      light: 'string',
      deep: 'string',
      normal: 'string',
      most: 'string',
      more: 'string',
      main: 'string',
      second: 'string',
      sub: 'string',
      last: 'string',
    }),
  },
  colors: {
    ...Status({
      default: 'string',
      light: 'string',
      deep: 'string',
      normal: 'string',
      most: 'string',
      more: 'string',
      main: 'string',
      second: 'string',
      sub: 'string',
      last: 'string',
    }),
    ...Actions({
      force: '#db2f2f',
      strong: '#db2f2f',
      care: '#f3d23a',
      relax: '#ffffff',
      prefer: '',
      ban: '',
    }),
    border: Status({
      default: 'string',
      light: 'string',
      deep: 'string',
      normal: 'string',
      most: 'string',
      more: 'string',
      main: 'string',
      second: 'string',
      sub: 'string',
      last: 'string',
    }),
    hover: Status({
      default: 'string',
      light: 'string',
      deep: 'string',
      normal: 'string',
      most: 'string',
      more: 'string',
      main: 'string',
      second: 'string',
      sub: 'string',
      last: 'string',
    }),
    focus: Status({
      default: 'string',
      light: 'string',
      deep: 'string',
      normal: 'string',
      most: 'string',
      more: 'string',
      main: 'string',
      second: 'string',
      sub: 'string',
      last: 'string',
    })
  },
  shadow: {
    ...Status({
      default: 'string',
      light: 'string',
      deep: 'string',
      normal: 'string',
      most: 'string',
      more: 'string',
      main: 'string',
      second: 'string',
      sub: 'string',
      last: 'string',
    }),
  },
  sizes: {
    ...Sizes({
      base: '0.1rem',
      bit: '0.1rem',
      mini: '0.2rem',
      small: '0.5rem',
      medium: '1rem',
      large: '1.5rem',
      huge: '2rem',
      super: '2.5rem',
    }),
    border: Sizes({
      base: '0.1rem',
      bit: '0.1rem',
      mini: '0.2rem',
      small: '0.3rem',
      medium: '0.5rem',
      large: '0.6rem',
      huge: '1rem',
      super: '1.5rem',
    }),
    radius: Sizes({
      base: '0.1rem',
      bit: '0.5rem',
      mini: '0.8rem',
      small: '1rem',
      medium: '1.5rem',
      large: '2rem',
      huge: '50%',
      super: '100%',
    }),
    padding: Sizes({
      base: '0.2rem 0.3rem',
      bit: '0.1rem 0.1rem',
      mini: '0.1rem 0.2rem',
      small: '0.2rem 0.3rem',
      medium: '0.3rem 0.5rem',
      large: '0.4rem 0.8rem',
      huge: '0.6rem 1rem',
      super: '1rem 2rem',
    }),
    padLeft: PubSizing,
    padRight: PubSizing,
    padTop: PubSizing,
    padBottom: PubSizing,
    padX: PubSizing,
    padY: PubSizing,
    margin: Sizes({
      base: '0.5rem 0.5rem',
      bit: '0.1rem 0.1rem',
      mini: '0.1rem 0.2rem',
      small: '0.2rem 0.3rem',
      medium: '0.3rem 0.5rem',
      large: '0.4rem 0.8rem',
      huge: '0.6rem 1rem',
      super: '1rem 2rem',
    }),
    marLeft: PubSizing,
    marRight: PubSizing,
    marTop: PubSizing,
    marBottom: PubSizing,
    marX: PubSizing,
    marY: PubSizing,
  }
}
